/*
 * APRSTelemetry.h
 *
 *  Created on: 2017-11-28
 *      Author: Vilius, LY3FF
 */

#ifndef APRSTELEMETRY_H_
#define APRSTELEMETRY_H_

#ifndef TELEMETRY_PACKET_INTERVAL
# define	TELEMETRY_PACKET_INTERVAL 60
#endif

class APRSTelemetry{
    // KISS -- Keep It Simple Stupid
    /*
     * Analog channel 1 - Battery Voltage
     * Analog channel 2 - Inside temperature
     * Analog channel 3 - Outside temperature
     *
     * 8 digital channels
     *
     * every digital channel is set as literal 1 or 0 directly in bits[8] char array.
     * Later we just add this array to the telemetry packet end
     *
     * Note: Again, the field widths are not all the same, and the byte counts include the comma separators
     * where shown. The list can terminate after any field.
    */

    private:
	void (*send_packet__)() = nullptr;

    unsigned char _sequence_number = 0;
    unsigned char _temperature[2] = { 0, 0 };	// generated temperature bytes for telemetry out.
    unsigned char _t_voltage = 0;				// generated byte for telemetry output

    double _battery_voltage=0;			// actual battery voltage
    unsigned char _packet_to_send   = 0;	// which packet will be sent next (units, params, eqns)
    unsigned int _ts_packet_to_send = 0;
    unsigned int _ts_read_sensors = 0; //
    unsigned int _ts_telemetry_packet = 0;

    public:
    char _packet_buffer[80];
    int _packet_length = 0;
    char _bits[9] = { '0', '0', '0', '0', '0', '0', '0', '0', 0 };

    // const ?
    const char *_tpn;		// TELEMETRY_PARAM_NAMES
    const char *_tpu;		// TELEMETRY_PARAM_UNITS
    const char *_tpe;		// TELEMETRY_PARAM_EQUATIONS;

    void setup();
    void loop();
    void setBit(unsigned char bit, bool state);
    bool getBit(unsigned char bit);
    void setBatteryVoltage(double voltage)	{ this->_battery_voltage = voltage; }
    void updateBatteryVoltage();
    void updateTemperatures(int temp1, int temp2);
    void generateTelemetryPacket();
    void generateParametersPacket();
    void generateUnitsPacket();
    void generateEQNSPacket();
    void sendTelemetryPacket();

    void setSendPacketCallback(void (* send_packet_callback)()){ this->send_packet__ = send_packet_callback;}

};




#endif
